language: node_js
node_js:
  - 12
install:
  - npm i -g lerna
  - lerna bootstrap
script:
  - npm run build
  - cd packages/sqrs && yarn lint && cd ../..
  - cd packages/sqrs-inversify && yarn lint && cd ../..
  - cd packages/example-project && yarn lint && cd ../..
  - yarn lint
